#pragma once
#include <iostream>
#include <cstdlib>
#include <unistd.h>
#include <fcntl.h>
#include <thread>
#include <algorithm>
#include <sys/stat.h>
#include <queue>
#include <vector>
#include <netinet/tcp.h> 
#include <mutex>
#include <signal.h>
#include <unordered_map>
#include <functional>
#include <condition_variable>
#include <json/json.h>
#include <hiredis/hiredis.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <aio.h>
#include <string>
#include <chrono>
#include <fstream>
#include <cstdio>
#include <termios.h>
#include <atomic>
#include <sys/sendfile.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>

#include "vector.hpp"
#include "queue.hpp"
#include "proto.hpp"
#include "IO.hpp"
#include "json.hpp"
#include "sock.hpp"
#include "database.hpp"
#include "epoll.hpp"

#include "../client/group.hpp"
#include "../client/friend.hpp"
#include "../client/inside.hpp"
#include "../client/menu.hpp"
#include "../client/client.hpp"

#include "../server/logic.hpp"
#include "../server/server.hpp"
